# Generated by Django 4.2 on 2024-10-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_aboutus_options_remove_aboutus_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
