# Generated by Django 4.2 on 2024-10-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0003_remove_aboutus_created_at_remove_aboutus_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
    ]
