# Generated by Django 4.2 on 2024-10-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Customer Email', 'verbose_name_plural': 'Customer Emails'},
        ),
    ]
