# Generated by Django 5.0.7 on 2024-08-19 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_maker_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.maker'),
        ),
    ]
